"""empty message

Revision ID: 1e03e05f825a
Revises: 58acc5f88987
Create Date: 2026-05-13 20:38:19.327175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e03e05f825a'
down_revision: Union[str, Sequence[str], None] = '58acc5f88987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backups', sa.Column('name_to_show', sa.String(), nullable=False))
    op.add_column('backups', sa.Column('rows', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backups', 'rows')
    op.drop_column('backups', 'name_to_show')
    # ### end Alembic commands ###
