"""edited backups table

Revision ID: 2e43401663bd
Revises: 30ca20228652
Create Date: 2026-06-15 12:51:29.296973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e43401663bd'
down_revision: Union[str, Sequence[str], None] = '30ca20228652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backups', sa.Column('pinned', sa.Boolean(), nullable=False))
    op.add_column('backups', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('backups', 'name_to_show')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backups', sa.Column('name_to_show', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('backups', 'name')
    op.drop_column('backups', 'pinned')
    # ### end Alembic commands ###
